### ISSUE TITLE
Trying TransformerNetworkTanh and error when running train.py

### ISSUE THREAD

**Issue by eformx** [iamRusty/fast-neural-style-pytorch#20]
Getting following error when trying. Hope you can help resolve this?

`Device:  cuda
Traceback (most recent call last):
  File "C:\Temp\fast-neural-style-pytorch-master\train.py", line 172, in <module>
    train()
  File "C:\Temp\fast-neural-style-pytorch-master\train.py", line 52, in train
    TransformerNetwork = transformer.TransformerNetworkTanh.to(device)
  File "C:\Users\eform\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 673, in to
    return self._apply(convert)
AttributeError: 'str' object has no attribute '_apply'`

**Comment by eformx** [comment]
solved. installed lasted version of pip transformers and issue resolved.
